# Generated by Django 4.2.5 on 2023-10-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishers',
            old_name='books',
            new_name='blogs',
        ),
    ]
